### ISSUE TITLE
Doesn't hide borders on form/stance bars

### ISSUE THREAD

**Issue by Sconethief** [emallson/HideActionBarBorders#1]
I checked with both druid and warrior and they still have the borders.
![image](https://user-images.githubusercontent.com/117250883/199395730-0df5d8cb-59cf-4e40-b4ac-cbd9b4861257.png)
![image](https://user-images.githubusercontent.com/117250883/199395917-a4c683f8-f409-4c92-a86d-c8769f946752.png)

**Comment by emallson** [comment]
Looks like I missed the stance bar.

**Comment by emallson** [comment]
This is fixed in version 1.0.1, which should be up soon
