### ISSUE TITLE
Spell have different width

### ISSUE THREAD

**Issue by MR-KOKOS** [emallson/HideActionBarBorders#3]
Hi,
I am using  Clean Icons - Mechagnome Edition and some of the spells are off by 1px for me.

Example:
![image](https://github.com/user-attachments/assets/af907907-14d1-4a97-bc1d-e3bebe837e6a)

Some of the spell icons are 66px x 66px and some of them are 67px x 67px.

I am using 1440p resolution and the Icon Size is 100%.

It triggers my OCD and I don't know if the issue is with the Clean Icons or with the HideActionBarBorders addon.

**Comment by SipeP** [comment]
I think i have figured it out:
Because of how UI scaling works in the game, you can end up with weird "half pixels" if your interface to screen resolution ratio is not exactly correct.

My UI scale was set to 80% and that didn't work well for my resolution.

**Comment by MR-KOKOS** [comment]
I think i have figured it out:
Because of how UI scaling works in the game, you can end up with weird "half pixels" if your interface to screen resolution ratio is not exactly correct.

My UI scale was set to 80% and that didn't work well for my resolution.

**Comment by emallson** [comment]
I've run into that exact problem before. It's *infuriating*
